version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo "Zip lambda functions from github repo"
      - zip -r9 index-photos.zip index-photos.py
      - zip -r9 search-photos.zip search-photos.py
  post_build:
    commands:
      - echo "Updating lambda Functions in aws"
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip
  artifacts:
    files: imagedefinitions.json
